name: PrimeChat
version: 1.2.0
main: corp.prime.chat.PrimeChat
api-version: '1.21'

author: PrimeDev
description: Modern and customizable Minecraft chat formatter by PrimeDev

softdepend:
  - PlaceholderAPI

commands:

  primechat:
    description: Управление PrimeChat
    usage: /primechat <help|reload|version>
    permission: primechat.admin

  ac:
    description: Админский чат
    usage: /ac <сообщение>
    aliases:
      - adminchat

permissions:

  primechat.admin:
    description: Административные команды PrimeChat
    default: op

  primechat.chatcolor:
    description: Позволяет использовать цвета и форматирование в чате
    default: false