name: PrimeChat
version: 1.3.0
main: corp.prime.chat.PrimeChat
api-version: '1.21'

author: PrimeDev
description: Modern and customizable Minecraft chat formatter by PrimeDev

softdepend:
  - PlaceholderAPI

commands:
  primechat:
    description: Управление PrimeChat
    usage: /primechat <help|reload|version>
    aliases:
      - pchat
      - pc
    permission: primechat.admin
  ac:
    description: Админский чат
    usage: /ac <сообщение>
    aliases:
      - adminchat
  msg:
    description: Личное сообщение игроку
    usage: /msg <игрок> <сообщение>
    aliases:
      - m
      - message
  r:
    description: Ответить на последнее личное сообщение
    usage: /r <сообщение>
    aliases:
      - reply
  socialspy:
    description: Просмотр личных сообщений
    usage: /socialspy
    aliases:
      - ss
    permission: primechat.socialspy
  commandspy:
    description: Просмотр команд игроков
    usage: /commandspy
    aliases:
      - cs
    permission: primechat.commandspy
  clearchat:
    description: Очистить чат
    usage: /clearchat
    aliases:
      - cc
    permission: primechat.clearchat
  afk:
    description: Статус AFK
    usage: /afk
    permission: primechat.afk

permissions:
  primechat.admin:
    description: Административные команды PrimeChat
    default: op
  primechat.chatcolor:
    description: Позволяет использовать цвета и форматирование в чате
    default: false
  primechat.msg:
    description: Позволяет использовать личные сообщения
    default: true
  primechat.socialspy:
    description: Позволяет включать SocialSpy
    default: op
  primechat.commandspy:
    description: Позволяет включать CommandSpy
    default: op
  primechat.clearchat:
    description: Позволяет очищать чат
    default: op
  primechat.afk:
    description: Позволяет использовать AFK
    default: true
  primechat.commandcontrol.bypass:
    description: Обход ограничений команд
    default: op
  primechat.commanddelay.reduce:
    description: Уменьшает задержку команд
    default: false
  primechat.commanddelay.bypass:
    description: Полностью отключает задержку команд
    default: op
